system:
  w: 600 nm
  layers:
    - name: air_left
      thickness: inf
      ex: 1.0
      ez: 1.0
      mu: 1

    - name: layer_A
      thickness: 200  # нм
      ex: 1.45
      ez: 1.45
      mu: 1

    - name: air_right
      thickness: inf
      ex: 1.0
      ez: 1.0
      mu: 1
