system:
  w: 780 nm
  layers:
    - name: air
      thickness: inf
      ex: 1
      ez: 1
      mu: 1
    - name: Au
      thickness: 300
      ex: !!python/complex -21.19+0.7361j
      ez: !!python/complex -21.19+0.7361j
      mu: 1
    - name: air
      thickness: inf
      ex: 1
      ez: 1
      mu: 1
