system:
  w: "780 nm"
  layers:
    - name: glass_top
      thickness: inf
      ex: 2.310
      ez: 2.310
      mu: 1
    - name: iceland_spar
      thickness: 225
      ex: 2.21
      ez: 2.21
      mu: 1
    - name: Au
      thickness: 75
      ex: !!python/complex -21.19+0.7361j
      ez: !!python/complex -21.19+0.7361j
      mu: 1
    - name: glass_bottom
      thickness: inf
      ex: 2.310
      ez: 2.310
      mu: 1